name: run_performance_tests_windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_performance_tests_windows:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.x
      - name: Run performance tests
        run: dotnet run -c Release --framework net9.0
        working-directory: ./csharp/PhoneNumbers.PerformanceTest
