name: "run_all_tests_and_upload_code_coverage"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_all_tests_and_upload_code_coverage:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Add key.snk for strong name signing
        run: |
          echo "${{ secrets.KEY_SNK_B64 }}" | Out-File key.snk.b64
          certutil -decode -f key.snk.b64 key.snk
      - name: Add zip files required for running tests
        run: |
          Compress-Archive -Path "resources\geocoding\*" -DestinationPath "resources\geocoding.zip"
          Compress-Archive -Path "resources\test\geocoding\*" -DestinationPath "resources\test\testgeocoding.zip"
      - name: Run tests
        run: dotnet test csharp/PhoneNumbers.sln --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: twcclegg/libphonenumber-csharp
