name: run_performance_tests_windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_performance_tests_windows:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Add key.snk for strong name signing
        run: |
          echo "${{ secrets.KEY_SNK_B64 }}" | Out-File key.snk.b64
          certutil -decode -f key.snk.b64 key.snk
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Run performance tests
        run: dotnet run -c Release --framework net9.0
        working-directory: ./csharp/PhoneNumbers.PerformanceTest
